"""Re-export inline keyboards (канон — builders.py)."""

from app.bot.keyboards.builders import (
    CAMPAIGNS_PER_PAGE,
    PER_PAGE_DEFAULT,
    accounts_pick_keyboard,
    campaign_confirm_keyboard,
    campaign_detail_keyboard,
    campaign_preset_keyboard,
    campaigns_list_keyboard,
    chats_multiselect_keyboard,
    nav_row,
    paginated_section_keyboard,
    section_accounts_keyboard,
    section_chats_keyboard,
    section_proxy_keyboard,
    section_templates_keyboard,
    dashboard_inline_keyboard,
    setup_gap_keyboard,
    templates_pick_keyboard,
)

__all__ = [
    "CAMPAIGNS_PER_PAGE",
    "PER_PAGE_DEFAULT",
    "accounts_pick_keyboard",
    "campaign_confirm_keyboard",
    "campaign_detail_keyboard",
    "campaign_preset_keyboard",
    "campaigns_list_keyboard",
    "dashboard_inline_keyboard",
    "chats_multiselect_keyboard",
    "nav_row",
    "paginated_section_keyboard",
    "section_accounts_keyboard",
    "section_chats_keyboard",
    "section_proxy_keyboard",
    "section_templates_keyboard",
    "setup_gap_keyboard",
    "templates_pick_keyboard",
]
